### ISSUE TITLE
Date + Weekday Name

### ISSUE THREAD

**Issue by Vipale** [shells-dw/loupedeck-worldclock#1]
I am just playing around with another of your plugins ;) Looks nice too. 
There seems to be a bug with the "Date + Weekday Name" it is only showing the name of the action.

Same for "Time + Date + Weekday Name (24h format)"
So i guess it's because of the weekday, I am using German as display language.

**Comment by shells-dw** [comment]
I noticed as well, thanks.

**Comment by shells-dw** [comment]
fixed with [v1.3.0](https://github.com/shells-dw/loupedeck-worldclock/releases/tag/v1.3.0)
